### ISSUE TITLE
There is no EMG data when I used two myo...

### ISSUE THREAD

**Issue by setowenGit** [mark-toma/MyoMex#20]
It is peculiar that the EMG data disappears when I use two Myo devices, whereas it works fine with just one. The IMU data and other aspects seem unaffected; only the EMG data is missing. Could you please provide me with some guidance on this matter?

**Comment by mark-toma** [comment]
This is a known limitation resulting from my implementation and benchmarking I performed during development.

From what I can remember, this is due to limitations in bandwidth to pass all IMU and EMG data for two devices through MEX. Streaming only EMG from two devices results in increasing lag. Since this isn't an issue with the lower throughput of IMU from two devices, I decided to discard EMG data when using two devices.

If you'd like to fork and hack on which data is provided, you can start here in the CPP MEX file:

https://github.com/mark-toma/MyoMex/blob/master/MyoMex/myo_mex/myo_mex.cpp#L237

Then the data object is passed back up to m code and into MyoData.addData here:

https://github.com/mark-toma/MyoMex/blob/master/MyoMex/MyoData.m#L393

I think if you just changed the calculations of sz[IMU|EMG][1|2] you could get any combo of IMU/EMG data from device 1 or 2. Good luck!
